name: Deploy Develop
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply configuration
        run: |
          git clone https://oauth2:${{ secrets.CONFIG_REPOSITORY_TOKEN }}@github.com/meetdy/infrastructure-config.git
          [ -e .env ] && rm .env
          [ -e Dockerfile ] && rm Dockerfile
          [ -e nginx.conf ] && rm nginx.conf
          [ -e .dockerignore ] && rm .dockerignore
          cp -a infrastructure-config/develop/meetdy-frontend/. ./
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set version variable
        id: vars
        run: echo "VERSION=1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build the Docker image with both tags
        run: |
          docker build . --file Dockerfile --tag nghiaphamln/meetdy-frontend:dev-1.${{ env.VERSION }} --tag nghiaphamln/meetdy-frontend:dev-latest

      - name: Push the Docker image to Docker Hub
        run: |
          docker push nghiaphamln/meetdy-frontend:dev-1.${{ env.VERSION }}
          docker push nghiaphamln/meetdy-frontend:dev-latest

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Deployment in K3s
        run: |
          kubectl rollout restart deployment/meetdy-frontend -n meetdy-develop
